import { editorDriver } from './test-support/editor-driver';
import katex from 'katex';
import { app, BrowserWindow } from 'electron';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { registerVaultIpcHandlers } from '../src/main/vault-ipc';
import { VaultRepository } from '../src/main/vault-repository';

async function main() {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'yantra-math-'));
  const userData = path.join(root, 'user-data');
  const vault = path.join(root, 'Math vault');
  await fs.mkdir(userData); await fs.mkdir(vault);
  app.setPath('userData', userData);
  await app.whenReady();
  const repo = await VaultRepository.open(vault, true);
  const file = await repo.createDocument('');
  await repo.saveDocument({ ...file.document, doc: { type: 'doc', content: [
    { type: 'heading', attrs: { level: 1 } }, { type: 'paragraph' },
  ] } });
  const canvas = await repo.createCanvas('');
  const nodeId = crypto.randomUUID();
  await repo.saveCanvas({ ...canvas.canvas, nodes: [{ id: nodeId, kind: 'document', documentId: file.document.id, x: 80, y: 80, width: 400, height: 300 }], layerOrder: [nodeId] });
  await fs.writeFile(path.join(userData, 'vault-preferences.json'), JSON.stringify({ lastVault: vault }));
  registerVaultIpcHandlers();
  const win = new BrowserWindow({ show: false, width: 1200, height: 800, webPreferences: {
    preload: path.resolve('dist-electron/preload.cjs'), contextIsolation: true, nodeIntegration: false, backgroundThrottling: false,
  } });
  const { evaluate, wait, click, edit } = editorDriver(win);
  const typeSource = async (source: string) => {
    await evaluate(`document.querySelector('.equation-dialog textarea').focus(); document.querySelector('.equation-dialog textarea').select()`);
    await win.webContents.insertText(source);
  };
  await win.loadFile(path.resolve('dist/index.html'));
  await wait(`!!document.querySelector('[data-path="${file.path}"]')`);
  await click(file.path);
  await wait(`!!document.querySelector('[contenteditable=true]')`);
  await edit(`editor.commands.setTextSelection(1)`);
  assert.equal(await evaluate(`document.querySelector('[aria-label="Insert equation"]').matches(':disabled')`), true);
  await edit(`editor.commands.setTextSelection(3)`);
  await click('Insert equation');
  await wait(`!!document.querySelector('.equation-dialog[open]')`);
  await typeSource('\\frac{a}{b}');
  await wait(`!!document.querySelector('.equation-dialog__preview .katex')`);
  await click('Save');
  await wait(`!!document.querySelector('[contenteditable=true] [data-type="inline-math"] .katex')`);
  await click('Undo');
  await wait(`!document.querySelector('[contenteditable=true] [data-type="inline-math"]')`);
  await click('Redo');
  await wait(`!!document.querySelector('[contenteditable=true] [data-type="inline-math"]')`);
  await evaluate(`document.querySelector('[contenteditable=true] [data-type="inline-math"]').click()`);
  await wait(`!!document.querySelector('.equation-dialog[open]')`);
  await typeSource('discard me');
  await click('Cancel');
  assert.equal(await edit(`return editor.getJSON().content[1].content[0].attrs.latex`), '\\frac{a}{b}');
  await edit(`editor.commands.setTextSelection(4)`);
  await click('Insert equation');
  await wait(`!!document.querySelector('.equation-dialog[open]')`);
  await evaluate(`(() => { const s = document.querySelector('.equation-dialog select'); s.value = 'blockMath'; s.dispatchEvent(new Event('change', { bubbles: true })); })()`);
  await typeSource('E=mc^2');
  await click('Save');
  await wait(`!!document.querySelector('[contenteditable=true] [data-type="block-math"] .katex-display')`);
  await wait(`!!document.querySelector('[aria-label="Saved"]')`);
  assert.match(await fs.readFile(path.join(vault, file.path), 'utf8'), /E=mc\^2/);
  await click(canvas.path);
  await wait(`document.querySelectorAll('.markdown-node__preview .katex-mathml').length === 2`);
  await evaluate(`document.querySelector('.markdown-node__body').dispatchEvent(new MouseEvent('dblclick', { bubbles: true }))`);
  await wait(`!!document.querySelector('.markdown-node [contenteditable=true]')`);
  await evaluate(`document.querySelector('[contenteditable=true] [data-type="block-math"]').click()`);
  await wait(`!!document.querySelector('.equation-dialog[open]')`);
  await typeSource('\\frac{');
  await click('Save');
  await wait(`!!document.querySelector('[contenteditable=true] .katex-error')`);
  await wait(`!!document.querySelector('[aria-label="Saved"]')`);
  await fs.writeFile(path.join(root, 'canvas.png'), (await win.webContents.capturePage()).toPNG());
  await win.reload();
  await wait(`!!document.querySelector('[data-path="${canvas.path}"]')`);
  await click(canvas.path);
  await wait(`!!document.querySelector('.markdown-node__preview .katex-error')`);
  await click(file.path);
  await wait(`!!document.querySelector('[contenteditable=true] .katex-error')`);
  await evaluate(`document.querySelector('[contenteditable=true] [data-type="block-math"]').click()`);
  await wait(`!!document.querySelector('.equation-dialog[open]')`);
  assert.equal(await evaluate(`document.querySelector('.equation-dialog textarea').value`), '\\frac{');
  await new Promise(resolve => setTimeout(resolve, 200));
  await fs.writeFile(path.join(root, 'dialog.png'), (await win.webContents.capturePage()).toPNG());
  await click('Cancel');
  const resetBody = async () => {
    await edit(`editor.commands.setContent({ type: 'doc', content: [{ type: 'heading', attrs: { level: 1 } }, { type: 'paragraph' }] }); editor.commands.setTextSelection(3); editor.commands.focus();`);
  };
  const paste = (text: string, html = '') => evaluate(`(() => {
    const data = new DataTransfer(); data.setData('text/plain', ${JSON.stringify(text)});
    if (${JSON.stringify(html)}) data.setData('text/html', ${JSON.stringify(html)});
    document.querySelector('[contenteditable=true]').dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }));
  })()`);
  const countMath = () => edit(`let count = 0; editor.state.doc.descendants(n => { if (n.type.name === 'inlineMath' || n.type.name === 'blockMath') count++; }); return count;`);
  await resetBody();
  await paste('## Physics\n\n**Force** $F=ma$ and `F=ma`.\n\n> Energy \\(E=mc^2\\).\n\n```math\n\\frac{a}{b}\n```');
  assert.equal(await countMath(), 3);
  assert.equal(await edit(`return editor.getJSON().content.some(n => n.type === 'blockquote')`), true);
  await click('Undo');
  assert.equal(await countMath(), 0);
  await click('Redo');
  assert.equal(await countMath(), 3);
  await edit(`let pos = 0; editor.state.doc.descendants((n, p) => { if (n.marks.some(m => m.type.name === 'code')) pos = p; }); editor.commands.setTextSelection(pos + 1);`);
  await click('Convert to equation');
  await wait(`!!document.querySelector('.equation-dialog[open]')`);
  assert.equal(await evaluate(`document.querySelector('.equation-dialog textarea').value`), 'F=ma');
  await click('Save');
  assert.equal(await countMath(), 4);
  await resetBody();
  const richMath = `<p><strong>Before</strong> ${katex.renderToString('x^2')} after <code>F=ma</code></p>${katex.renderToString('y^2', { displayMode: true })}`;
  await paste('plain fallback must not replace rich content', richMath);
  assert.equal(await countMath(), 2);
  assert.equal(await evaluate(`document.querySelectorAll('[contenteditable=true] .katex-mathml').length`), 2);
  assert.equal(await edit(`return editor.state.doc.textContent.includes('Before') && editor.state.doc.textContent.includes('after')`), true);
  const copied = await edit(`editor.commands.setTextSelection({ from: 3, to: editor.state.doc.content.size }); const value = editor.view.serializeForClipboard(editor.state.selection.content()); return { html: value.dom.innerHTML, text: value.text };`);
  assert.match(copied.text, /\\\(x\^2\\\)/);
  await resetBody();
  await paste(copied.text, copied.html);
  assert.equal(await countMath(), 2);
  await resetBody();
  await paste('fallback', '<p>A <span data-math-source="z^2"><span class="katex"><math><semantics><annotation encoding="application/x-tex">z^2</annotation></semantics></math><span>duplicate visual z</span></span></span> B</p><pre><code class="language-math">a+b</code></pre>');
  assert.equal(await countMath(), 2);
  assert.equal(await edit(`return editor.state.doc.textContent.includes('duplicate')`), false);
  await resetBody();
  await paste('Price $5 and $10. Escaped \\$x$ and `F=ma`.');
  assert.equal(await countMath(), 0);
  await resetBody();
  await edit(`editor.commands.insertContent({ type: 'text', text: 'code', marks: [{ type: 'code' }] }); editor.commands.setTextSelection(5);`);
  await paste('$x$', richMath);
  assert.equal(await countMath(), 0);
  assert.equal(await edit(`return editor.state.doc.textContent.includes('$x$')`), true);
  await resetBody();
  await paste('fallback', '<p><strong>Bold</strong> <a href="https://example.com">link</a></p>');
  assert.equal(await evaluate(`document.querySelector('[contenteditable=true] strong')?.textContent`), 'Bold');
  assert.equal(await countMath(), 0);
  await resetBody();
  await edit(`editor.commands.setCodeBlock()`);
  await paste('$x$\n```math\ny\n```');
  assert.equal(await countMath(), 0);
  assert.equal(await edit(`return editor.state.doc.child(1).type.name`), 'codeBlock');
  await resetBody();
  await evaluate(`document.querySelector('[contenteditable=true]').dispatchEvent(new KeyboardEvent('keydown', { key: 'Shift', keyCode: 16, shiftKey: true, bubbles: true }))`);
  await paste('$x$');
  await evaluate(`document.querySelector('[contenteditable=true]').dispatchEvent(new KeyboardEvent('keyup', { key: 'Shift', keyCode: 16, bubbles: true }))`);
  assert.equal(await countMath(), 0);
  await resetBody();
  await edit(`editor.commands.setTextSelection(1)`);
  await paste('$x$');
  assert.equal(await countMath(), 0);
  await resetBody();
  await paste('A $x^2$.\n\n$$\ny^2\n$$');
  assert.equal(await countMath(), 2);
  await wait(`!!document.querySelector('[aria-label="Saved"]')`);
  await click(canvas.path);
  await wait(`document.querySelectorAll('.markdown-node__preview .katex-mathml').length === 2`);
  await evaluate(`document.querySelector('.markdown-node__body').dispatchEvent(new MouseEvent('dblclick', { bubbles: true }))`);
  await wait(`!!document.querySelector('.markdown-node [contenteditable=true]')`);
  await edit(`editor.commands.insertContentAt(editor.state.doc.content.size, { type: 'paragraph' }); editor.commands.setTextSelection(editor.state.doc.content.size - 1); editor.commands.focus();`);
  await paste('Canvas \\(z^2\\)');
  assert.equal(await countMath(), 3, await edit(`return JSON.stringify({ doc: editor.getJSON(), selection: editor.state.selection.toJSON() })`));
  await wait(`!!document.querySelector('[aria-label="Saved"]')`);
  await win.reload();
  await wait(`!!document.querySelector('[data-path="${canvas.path}"]')`);
  await click(canvas.path);
  await wait(`document.querySelectorAll('.markdown-node__preview .katex-mathml').length === 3`);
  // Idle nodes leave the DOM offscreen, while a live editor retains its session.
  const panAway = () => win.webContents.sendInputEvent({ type: 'mouseWheel', x: 1100, y: 100, deltaX: 5000, deltaY: 0, canScroll: true });
  panAway();
  await wait(`document.querySelectorAll('.react-flow__node').length === 0`);
  await evaluate(`document.querySelector('.react-flow__controls-fitview').click()`);
  await wait(`document.querySelectorAll('.markdown-node__preview .katex-mathml').length === 3`);
  await evaluate(`document.querySelector('.markdown-node__body').dispatchEvent(new MouseEvent('dblclick', { bubbles: true }))`);
  await wait(`!!document.querySelector('.markdown-node [contenteditable=true]')`);
  await edit(`window.mathSmokeEditor = editor;`);
  panAway();
  await new Promise(resolve => setTimeout(resolve, 150));
  assert.equal(await edit(`return editor === window.mathSmokeEditor && !editor.isDestroyed`), true);
  await evaluate(`document.querySelector('.react-flow__controls-fitview').click()`);
  await wait(`!!document.querySelector('.markdown-node [contenteditable=true]')`);
  console.log(`Math UI smoke passed: ${root}`);
  win.destroy(); app.quit();
}
main().catch(error => { console.error(error); app.exit(1); });
