import { app, BrowserWindow } from 'electron';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { registerVaultIpcHandlers } from '../src/main/vault-ipc';
import { VaultRepository } from '../src/main/vault-repository';
import { installCloseFlushHandler } from '../src/main/close-flush';

async function main() {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'yantra-ui-smoke-'));
  const userData = path.join(root, 'user-data');
  await fs.mkdir(userData);
  app.setPath('userData', userData);
  await app.whenReady();
  app.on('window-all-closed', () => { /* Keep the test alive for disk assertions after close. */ });

  try {
    const vaultPath = path.join(root, 'Smoke vault');
    await fs.mkdir(vaultPath);
    const repository = await VaultRepository.open(vaultPath, true);
    await fs.mkdir(path.join(vaultPath, 'Research'));
    const first = await repository.createDocument('');
    await fs.writeFile(path.join(vaultPath, 'Broken.yantraD'), '{}');
    await repository.createFolder('', 'Trash_folder');
    await repository.createFolder('Trash_folder', 'Nested');
    await repository.createDocument('Trash_folder/Nested');
    await repository.createCanvas('Trash_folder');
    const trashDocument = await repository.createDocument('');
    const trashCanvas = await repository.createCanvas('');

    await fs.writeFile(path.join(userData, 'vault-preferences.json'), JSON.stringify({ lastVault: vaultPath }));
    registerVaultIpcHandlers();
    const window = new BrowserWindow({ width: 1280, height: 840, show: false, webPreferences: {
      preload: path.resolve('dist-electron/preload.cjs'), contextIsolation: true, nodeIntegration: false,
    } });
    installCloseFlushHandler(window);
    const evaluate = async (script: string) => {
      try { return await window.webContents.executeJavaScript(script); }
      catch (error) { throw new Error(`Renderer script failed: ${script}`, { cause: error }); }
    };
    async function waitFor(script: string, target = window) {
      for (let attempt = 0; attempt < 100; attempt += 1) {
        if (await target.webContents.executeJavaScript(script)) return;
        await new Promise((resolve) => setTimeout(resolve, 50));
      }
      throw new Error(`Timed out: ${script}\nFocus: ${await target.webContents.executeJavaScript('document.activeElement?.outerHTML.slice(0, 300)')}\n${await target.webContents.executeJavaScript('document.body.innerText')}`);
    }
    const click = (name: string) => evaluate(`Array.from(document.querySelectorAll('button')).find(b => b.getAttribute('aria-label') === ${JSON.stringify(name)} || b.textContent.trim() === ${JSON.stringify(name)}).click()`);
    const pointerClick = async (selector: string, offset = 8, pressMs = 50) => {
      const point = await evaluate(`(() => { const r = document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect(); return { x: Math.round(r.left + ${offset}), y: Math.round(r.top + ${offset}) }; })()`);
      window.webContents.sendInputEvent({ type: 'mouseMove', ...point });
      window.webContents.sendInputEvent({ type: 'mouseDown', ...point, button: 'left', clickCount: 1 });
      await new Promise((resolve) => setTimeout(resolve, pressMs));
      window.webContents.sendInputEvent({ type: 'mouseUp', ...point, button: 'left', clickCount: 1 });
    };
    await window.loadFile(path.resolve('dist/index.html'));
    assert.equal(await evaluate(`window.yantraDebug === undefined && window.yantraVaultTrace === undefined`), true);
    await waitFor(`document.querySelector('.vault-root')?.getAttribute('title') === 'Smoke vault /'`);
    assert.equal(await evaluate(`!!document.querySelector('[contenteditable=true]')`), false);
    const reorder = async (source: string, anchor: string, side: 'before' | 'after') => {
      await evaluate(`(() => {
        const row = Array.from(document.querySelectorAll('[data-path]')).find(row => row.dataset.path === ${JSON.stringify(source)});
        row.dispatchEvent(new DragEvent('dragstart', { bubbles: true, dataTransfer: new DataTransfer() }));
      })()`);
      await waitFor(`!!document.querySelector('.vault-tree__row--dragging')`);
      const dragEvent = `(() => {
        const row = Array.from(document.querySelectorAll('[data-path]')).find(row => row.dataset.path === ${JSON.stringify(anchor)});
        const rect = row.getBoundingClientRect();
        return { row, options: { bubbles: true, cancelable: true, dataTransfer: new DataTransfer(), clientX: rect.left + 20, clientY: ${JSON.stringify(side)} === 'before' ? rect.top + 1 : rect.bottom - 1 } };
      })()`;
      await evaluate(`(() => { const { row, options } = ${dragEvent}; row.dispatchEvent(new DragEvent('dragover', options)); })()`);
      await waitFor(`!!document.querySelector('.vault-tree__row--insert-${side}')`);
      await evaluate(`(() => { const { row, options } = ${dragEvent}; row.dispatchEvent(new DragEvent('drop', options)); })()`);
      await waitFor(`!document.querySelector('.vault-root').disabled && !document.querySelector('.vault-tree__row--dragging')`);
    };
    await reorder('Trash_folder', 'Research', 'before');
    assert.equal(await evaluate(`document.querySelector('.vault-tree > ul > li > button').dataset.path`), 'Trash_folder');
    await reorder(first.path, trashDocument.path, 'after');
    assert.equal(await evaluate(`(() => { const paths = Array.from(document.querySelectorAll('.vault-tree > ul > li > button')).map(row => row.dataset.path); return paths.indexOf(${JSON.stringify(first.path)}) > paths.indexOf(${JSON.stringify(trashDocument.path)}); })()`), true);
    await window.reload();
    await waitFor(`document.querySelector('.vault-tree > ul > li > button')?.dataset.path === 'Trash_folder'`);
    const contextMenu = async (relative: string) => {
      await evaluate(`Array.from(document.querySelectorAll('[data-path]')).find(row => row.dataset.path === ${JSON.stringify(relative)}).dispatchEvent(new MouseEvent('contextmenu', { bubbles: true, clientX: 100, clientY: 220 }))`);
      await waitFor(`!!document.querySelector('[role="menu"]')`);
      await click('Move to Trash');
      await waitFor(`!!document.querySelector('.vault-dialog--trash[open]')`);
    };
    await contextMenu(trashDocument.path);
    await click('Cancel');
    assert.equal(await evaluate(`!!document.querySelector('[data-path="' + ${JSON.stringify(trashDocument.path)} + '"]')`), true);
    await click(trashDocument.path);
    await waitFor(`!!document.querySelector('[contenteditable=true]')`);
    await contextMenu(trashDocument.path);
    await click('Move to Trash');
    await waitFor(`!document.querySelector('.vault-dialog[open]') && !document.querySelector('[contenteditable=true]')`);
    await assert.rejects(fs.stat(path.join(vaultPath, trashDocument.path)));
    await click(trashCanvas.path);
    await waitFor(`!!document.querySelector('.react-flow__pane')`);
    await contextMenu(trashCanvas.path);
    await click('Move to Trash');
    await waitFor(`!document.querySelector('.vault-dialog[open]') && !document.querySelector('.react-flow__pane')`);
    await assert.rejects(fs.stat(path.join(vaultPath, trashCanvas.path)));
    await click('Trash_folder');
    await contextMenu('Trash_folder');
    await new Promise((resolve) => setTimeout(resolve, 100));
    await fs.writeFile(path.join(root, 'delete-folder-dialog.png'), (await window.webContents.capturePage()).toPNG());
    await click('Move to Trash');
    await waitFor(`!document.querySelector('.vault-dialog[open]') && !document.querySelector('[data-path="Trash_folder"]')`);
    assert.equal(await evaluate(`document.querySelector('.vault-destination').textContent`), 'New file in: /');
    await assert.rejects(fs.stat(path.join(vaultPath, 'Trash_folder')));

    await click('Research');
    await click('New Document');
    await waitFor(`!!document.querySelector('[contenteditable=true]')`);
    await waitFor(`document.activeElement === document.querySelector('[contenteditable=true]')`);
    assert.equal(await evaluate(`getSelection().isCollapsed && getSelection().anchorOffset === 0 && document.activeElement.contains(getSelection().anchorNode)`), true);
    await window.webContents.insertText('Saved from the live editor');
    await waitFor(`document.querySelector('[aria-label="Saved"]') !== null`);
    let researchPath = path.join(vaultPath, 'Research', 'Untitled.yantraD');
    assert.match(await fs.readFile(researchPath, 'utf8'), /Saved from the live editor/);
    await evaluate(`Array.from(document.querySelectorAll('.vault-tree > ul > li > button')).find(b => b.textContent.trim() === ${JSON.stringify(first.path)}).click()`);
    await waitFor(`document.querySelector('[contenteditable=true]')?.textContent === ''`);
    await waitFor(`!!document.querySelector('[data-path="Research/Saved_from_the_live_editor.yantraD"]') && document.querySelector('.vault-workspace').getAttribute('aria-busy') === 'false'`);
    researchPath = path.join(vaultPath, 'Research', 'Saved_from_the_live_editor.yantraD');
    await evaluate(`document.querySelector('[contenteditable=true]').focus()`);
    await window.webContents.insertText('Independent second draft');
    // Select the other same-named file by its nested tree position.
    await evaluate(`document.querySelector('.vault-tree ul ul button').click()`);
    await waitFor(`document.querySelector('[contenteditable=true]')?.textContent === 'Saved from the live editor'`);
    await waitFor(`!!document.querySelector('[data-path="Independent_second_draft.yantraD"]') && document.querySelector('.vault-workspace').getAttribute('aria-busy') === 'false'`);
    first.path = 'Independent_second_draft.yantraD';
    await click('Broken.yantraD');
    await waitFor(`document.body.textContent.includes('Unable to open document')`);
    assert.equal(await evaluate(`!!document.querySelector('[contenteditable=true]')`), false);
    await evaluate(`document.querySelector('.vault-tree ul ul button').click()`);
    await waitFor(`!!document.querySelector('[contenteditable=true]')`);
    const savedFile = await fs.readFile(researchPath, 'utf8');
    await fs.unlink(researchPath);
    await evaluate(`document.querySelector('[contenteditable=true]').focus()`);
    await window.webContents.insertText(' retained after save failure');
    await waitFor(`!!document.querySelector('[aria-label="Failed"]')`);
    assert.match(await evaluate('document.body.innerText'), /Retry save/);
    await fs.writeFile(researchPath, savedFile);
    await click('Retry save');
    await waitFor(`!!document.querySelector('[aria-label="Saved"]')`);
    assert.match(await fs.readFile(researchPath, 'utf8'), /retained after save failure/);
    const nextResearchName = await evaluate(`document.querySelector('[contenteditable=true] h1').textContent.replaceAll(' ', '_')`);
    await click('New Canvas');
    await waitFor(`!!document.querySelector('.react-flow__pane') && !!document.querySelector('[data-path="Research/' + ${JSON.stringify(nextResearchName)} + '.yantraD"]') && document.querySelector('.vault-workspace').getAttribute('aria-busy') === 'false'`);
    researchPath = path.join(vaultPath, 'Research', `${nextResearchName}.yantraD`);
    await evaluate(`(() => { const pane = document.querySelector('.react-flow__pane'); const r = pane.getBoundingClientRect(); pane.dispatchEvent(new MouseEvent('dblclick', { bubbles: true, clientX: r.left + 350, clientY: r.top + 200 })); })()`);
    await waitFor(`document.querySelectorAll('.react-flow__node').length === 1 && !document.querySelector('[inert].vault-live-canvas')`);
    assert.equal(await evaluate(`!!document.querySelector('.markdown-node__editor')`), false);
    await evaluate(`document.querySelector('.markdown-node__body').dispatchEvent(new MouseEvent('dblclick', { bubbles: true }))`);
    await waitFor(`!!document.querySelector('.markdown-node [contenteditable=true]')`);
    await evaluate(`document.querySelector('.markdown-node [contenteditable=true]').focus()`);
    await window.webContents.insertText('Canvas document content');
    await waitFor(`!!document.querySelector('[aria-label="Saved"]')`);
    const canvasPath = path.join(vaultPath, 'Untitled.yantraC');
    let nodeDocumentPath = path.join(vaultPath, 'Unfiled', 'Untitled.yantraD');
    assert.match(await fs.readFile(nodeDocumentPath, 'utf8'), /Canvas document content/);
    assert.doesNotMatch(await fs.readFile(canvasPath, 'utf8'), /Canvas document content|"doc":/);
    await click('Open Document');
    await waitFor(`!document.querySelector('.react-flow') && !!document.querySelector('[contenteditable=true]') && document.querySelector('.vault-file-header h1')?.textContent === 'Canvas_document_content'`);
    assert.equal(await evaluate(`document.querySelector('[contenteditable=true]').textContent`), 'Canvas document content');
    await evaluate(`document.querySelector('[contenteditable=true]').focus()`);
    await window.webContents.insertText('Standalone update ');
    await click('Untitled.yantraC');
    await waitFor(`document.querySelector('.markdown-node__preview')?.textContent.includes('Standalone update') && document.querySelector('[aria-label="Open Document"]')?.title === 'Open Standalone_update_Canvas_document_content' && !document.querySelector('[inert].vault-live-canvas')`);
    await new Promise((resolve) => setTimeout(resolve, 100));
    const resize = await evaluate(`(() => { const r = document.querySelector('.react-flow__resize-control.handle.bottom.right').getBoundingClientRect(); return { x: Math.round(r.x + r.width / 2), y: Math.round(r.y + r.height / 2) }; })()`);
    window.webContents.sendInputEvent({ type: 'mouseMove', ...resize });
    window.webContents.sendInputEvent({ type: 'mouseDown', ...resize, button: 'left', clickCount: 1 });
    await new Promise((resolve) => setTimeout(resolve, 50));
    window.webContents.sendInputEvent({ type: 'mouseMove', x: resize.x + 100, y: resize.y + 60, button: 'left', modifiers: ['leftButtonDown'] });
    await new Promise((resolve) => setTimeout(resolve, 50));
    window.webContents.sendInputEvent({ type: 'mouseUp', x: resize.x + 100, y: resize.y + 60, button: 'left', clickCount: 1 });
    await waitFor(`document.querySelector('.react-flow__node').getBoundingClientRect().width > 400`);
    assert.equal(await evaluate(`document.querySelector('.react-flow__node').classList.contains('selected')`), true);
    assert.equal(await evaluate(`!!document.querySelector('.markdown-node__editor')`), false);
    await waitFor(`!!document.querySelector('[aria-label="Saved"]')`);
    await fs.writeFile(path.join(root, 'canvas-desktop.png'), (await window.webContents.capturePage()).toPNG());
    window.setSize(900, 620);
    await new Promise((resolve) => setTimeout(resolve, 100));
    await fs.writeFile(path.join(root, 'canvas-narrow.png'), (await window.webContents.capturePage()).toPNG());
    assert.equal(await evaluate(`document.documentElement.scrollWidth > innerWidth`), false);
    // Protected title behavior uses the same editor in nodes and documents.
    const editorAction = (script: string) => evaluate(`(() => { const editor = document.querySelector('[contenteditable=true]').editor; ${script} })()`);
    await evaluate(`document.querySelector('.markdown-node__body').dispatchEvent(new MouseEvent('dblclick', { bubbles: true }))`);
    await waitFor(`!!document.querySelector('.markdown-node [contenteditable=true]')`);
    await editorAction(`editor.commands.setTextSelection(1); editor.commands.focus();`);
    await waitFor(`document.querySelector('[aria-label="Bold"]').matches(':disabled')`);
    assert.equal(await editorAction(`return editor.state.doc.firstChild.type.name === 'heading' && editor.state.doc.firstChild.attrs.level === 1;`), true);
    await editorAction(`editor.commands.selectAll(); editor.commands.insertContent('A long title with English words that wraps across several lines in the canvas node'); editor.commands.setTextSelection(8);`);
    await waitFor(`document.querySelector('.markdown-node__prose h1')?.textContent === 'A long title with English words that wraps across several lines in the canvas node'`);
    await waitFor(`document.querySelector('[aria-label="Bold"]').matches(':disabled')`);
    assert.equal(await evaluate(`(() => { const title = document.querySelector('.markdown-node__prose h1'); return title.getBoundingClientRect().height > parseFloat(getComputedStyle(title).lineHeight) * 1.5; })()`), true);
    await evaluate(`new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))`);
    await fs.writeFile(path.join(root, 'protected-title-node.png'), (await window.webContents.capturePage()).toPNG());
    await window.webContents.insertText('123!');
    await waitFor(`!!document.querySelector('.document-title-error')`);
    assert.equal(await editorAction(`return editor.state.doc.firstChild.textContent.includes('123!');`), false);
    for (const type of ['keyDown', 'char', 'keyUp'] as const) window.webContents.sendInputEvent({ type, keyCode: 'Enter' });
    await waitFor(`!!document.querySelector('[contenteditable=true]') && !document.querySelector('[inert].vault-live-canvas') && !document.querySelector('[aria-label="Bold"]').matches(':disabled')`);
    await waitFor(`document.activeElement === document.querySelector('[contenteditable=true]')`);
    nodeDocumentPath = path.join(vaultPath, 'Unfiled', 'A_long_title_with_English_words_that_wraps_across_several_lines_in_the_canvas_node.yantraD');
    await fs.stat(nodeDocumentPath);
    await assert.rejects(fs.stat(path.join(vaultPath, 'Unfiled', 'Untitled.yantraD')), { code: 'ENOENT' });
    assert.equal(await editorAction(`return editor.state.doc.firstChild.textContent;`), 'A long title with English words that wraps across several lines in the canvas node');
    await window.webContents.insertText('Body 123!');
    await editorAction(`editor.commands.setTextSelection({ from: editor.state.doc.firstChild.nodeSize + 1, to: editor.state.doc.content.size - 1 });`);
    await click('Bold');
    assert.equal(await editorAction(`return editor.state.doc.child(1).firstChild.marks.some(mark => mark.type.name === 'bold');`), true);
    await click('Open Document');
    await waitFor(`!document.querySelector('.react-flow') && !!document.querySelector('[contenteditable=true]')`);
    assert.equal(await editorAction(`return editor.state.doc.child(1).textContent;`), 'Body 123!');
    await editorAction(`editor.commands.setTextSelection(editor.state.doc.firstChild.nodeSize + 1); editor.commands.setHeading({ level: 2 }); editor.commands.selectAll(); editor.commands.keyboardShortcut('Mod-Alt-0'); editor.commands.keyboardShortcut('Mod-b');`);
    assert.equal(await editorAction(`return editor.state.doc.child(1).attrs.level;`), 2);
    assert.equal(await editorAction(`return editor.state.doc.firstChild.firstChild.marks.length;`), 0);
    await editorAction(`editor.commands.setTextSelection({ from: 1, to: 1 + editor.state.doc.firstChild.content.size }); editor.commands.focus();`);
    await waitFor(`document.querySelector('[aria-label="Bold"]').matches(':disabled')`);
    await evaluate(`(() => { const data = new DataTransfer(); data.setData('text/plain', ${JSON.stringify('Pasted Title\nPasted body 42!')}); data.setData('text/html', '<h2><strong>Pasted Title</strong></h2><p>Pasted body 42!</p>'); document.querySelector('[contenteditable=true]').dispatchEvent(new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: data })); })()`);
    await waitFor(`document.querySelector('.vault-file-header h1')?.textContent === 'Pasted_Title' && !!document.querySelector('[contenteditable=true]')`);
    nodeDocumentPath = path.join(vaultPath, 'Unfiled', 'Pasted_Title.yantraD');
    assert.equal(await editorAction(`return editor.state.doc.firstChild.textContent;`), 'Pasted Title');
    assert.equal(await editorAction(`return editor.state.doc.firstChild.firstChild.marks.length;`), 0);
    assert.equal(await editorAction(`return editor.state.doc.child(1).textContent;`), 'Pasted body 42!');
    await editorAction(`editor.commands.setTextSelection(1); editor.commands.focus();`);
    await evaluate(`(() => { const data = new DataTransfer(); data.setData('text/plain', 'Invalid_123'); document.querySelector('[contenteditable=true]').dispatchEvent(new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: data })); })()`);
    await waitFor(`!!document.querySelector('.document-title-error')`);
    assert.equal(await editorAction(`return editor.state.doc.firstChild.textContent;`), 'Pasted Title');
    await evaluate(`new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))`);
    await fs.writeFile(path.join(root, 'protected-title-document.png'), (await window.webContents.capturePage()).toPNG());
    await editorAction(`editor.commands.selectAll(); editor.commands.deleteSelection();`);
    assert.equal(await editorAction(`return editor.state.doc.firstChild.type.name === 'heading' && editor.state.doc.firstChild.attrs.level === 1 && editor.state.doc.textContent === '';`), true);
    await editorAction(`editor.commands.undo();`);
    assert.equal(await editorAction(`return editor.state.doc.firstChild.textContent;`), 'Pasted Title');
    await waitFor(`!!document.querySelector('[aria-label="Saved"]')`);
    assert.match(await fs.readFile(nodeDocumentPath, 'utf8'), /Pasted Title/);
    assert.equal(await evaluate(`document.querySelector('.vault-file-header h1').textContent`), 'Pasted_Title');
    // A draft title does not rename while the caret remains in its title.
    assert.match(await fs.readFile(nodeDocumentPath, 'utf8'), /Pasted Title/);
    const commitEditorTitle = async (title: string, byClick = false) => {
      await editorAction(`editor.commands.setTextSelection({ from: 1, to: editor.state.doc.firstChild.nodeSize - 1 }); editor.commands.insertContent(${JSON.stringify(title)}); editor.commands.focus();`);
      if (byClick) await pointerClick('[contenteditable=true] > :nth-child(2)');
      else for (const type of ['keyDown', 'char', 'keyUp'] as const) window.webContents.sendInputEvent({ type, keyCode: 'Enter' });
      await waitFor(`!!document.querySelector('[contenteditable=true]') && document.querySelector('.vault-workspace').getAttribute('aria-busy') === 'false'`);
      await waitFor(`document.activeElement === document.querySelector('[contenteditable=true]')`);
    };
    await commitEditorTitle('Project 2026');
    await waitFor(`document.querySelector('.vault-file-header h1')?.textContent === 'Project_2026'`);
    nodeDocumentPath = path.join(vaultPath, 'Unfiled', 'Project_2026.yantraD');
    const takenPath = path.join(vaultPath, 'Unfiled', 'Taken_2.yantraD');
    const taken = { ...JSON.parse(await fs.readFile(nodeDocumentPath, 'utf8')), id: crypto.randomUUID(), title: 'Taken_2' };
    await fs.writeFile(takenPath, JSON.stringify(taken));
    await commitEditorTitle('Taken 2', true);
    await waitFor(`document.querySelector('[role="alert"]')?.textContent.includes('already exists')`);
    assert.equal(await evaluate(`document.querySelector('.vault-file-header h1').textContent`), 'Project_2026');
    assert.equal(await fs.readFile(takenPath, 'utf8'), JSON.stringify(taken));
    assert.match(await fs.readFile(nodeDocumentPath, 'utf8'), /Taken 2/);
    await fs.writeFile(path.join(root, 'title-collision.png'), (await window.webContents.capturePage()).toPNG());
    await commitEditorTitle('Project 2027');
    await waitFor(`document.querySelector('.vault-file-header h1')?.textContent === 'Project_2027' && !document.querySelector('[role="alert"]')`);
    nodeDocumentPath = path.join(vaultPath, 'Unfiled', 'Project_2027.yantraD');
    await window.webContents.insertText('Body after title commit ');
    await waitFor(`!!document.querySelector('[aria-label="Saved"]')`);
    assert.match(await fs.readFile(nodeDocumentPath, 'utf8'), /Body after title commit/);
    await commitEditorTitle('Clicked Body 1', true);
    await waitFor(`document.querySelector('.vault-file-header h1')?.textContent === 'Clicked_Body_1'`);
    assert.equal(await editorAction(`return editor.state.selection.from > editor.state.doc.firstChild.nodeSize;`), true);
    await editorAction(`editor.commands.setTextSelection({ from: 1, to: editor.state.doc.firstChild.nodeSize - 1 }); editor.commands.deleteSelection(); editor.commands.focus();`);
    await pointerClick('[contenteditable=true] > :nth-child(2)');
    await waitFor(`!!document.querySelector('[aria-label="Saved"]')`);
    assert.equal(await evaluate(`document.querySelector('.vault-file-header h1').textContent`), 'Clicked_Body_1');
    assert.equal(await editorAction(`return editor.state.doc.firstChild.textContent;`), '');
    await editorAction(`editor.commands.setTextSelection({ from: 1, to: editor.state.doc.firstChild.nodeSize - 1 }); editor.commands.insertContent('Clicked Away 2'); editor.commands.focus();`);
    await pointerClick('[data-path="Untitled.yantraC"]');
    await waitFor(`!!document.querySelector('.react-flow__pane') && !document.querySelector('[inert].vault-live-canvas') && document.querySelector('[aria-label="Open Document"]')?.title === 'Open Clicked_Away_2'`);
    assert.equal(await evaluate(`!!document.querySelector('[contenteditable=true]')`), false);
    await evaluate(`document.querySelector('.markdown-node__body').dispatchEvent(new MouseEvent('dblclick', { bubbles: true }))`);
    await waitFor(`!!document.querySelector('[contenteditable=true]')`);
    await editorAction(`editor.commands.setTextSelection({ from: 1, to: editor.state.doc.firstChild.nodeSize - 1 }); editor.commands.insertContent('Canvas Click 3'); editor.commands.focus();`);
    await pointerClick('.react-flow__pane', 20, 0);
    await waitFor(`!document.querySelector('[contenteditable=true]') && document.querySelector('[aria-label="Open Document"]')?.title === 'Open Canvas_Click_3'`);
    nodeDocumentPath = path.join(vaultPath, 'Unfiled', 'Canvas_Click_3.yantraD');
    assert.match(await fs.readFile(nodeDocumentPath, 'utf8'), /Canvas Click 3/);
    await evaluate(`document.querySelector('.vault-tree ul ul button').click()`);
    await waitFor(`!!document.querySelector('[contenteditable=true]')`);
    await fs.writeFile(path.join(root, 'desktop.png'), (await window.webContents.capturePage()).toPNG());
    window.setSize(900, 620);
    await new Promise((resolve) => setTimeout(resolve, 100));
    await fs.writeFile(path.join(root, 'narrow.png'), (await window.webContents.capturePage()).toPNG());
    assert.equal(await evaluate(`document.documentElement.scrollWidth > innerWidth`), false);
    await evaluate(`document.querySelector('[contenteditable=true]').focus()`);
    await window.webContents.insertText(' flushed on close');
    await new Promise<void>((resolve) => { window.once('closed', resolve); window.close(); });
    assert.match(await fs.readFile(researchPath, 'utf8'), /flushed on close/);
    assert.match(await fs.readFile(path.join(vaultPath, first.path), 'utf8'), /Independent second draft/);
    // Accept changes made through the live app before this fixture repository edits again.
    await repository.refresh();
    const canvas = await repository.readCanvas('Untitled.yantraC');
    assert.ok(canvas.nodes[0]!.width > 400);
    const secondNodeDocument = await repository.createNodeDocument();
    const secondNode = { ...canvas.nodes[0]!, id: crypto.randomUUID(), documentId: secondNodeDocument.document.id, x: 780 };
    const group = { id: crypto.randomUUID(), nodeIds: [canvas.nodes[0]!.id, secondNode.id] };
    await repository.saveCanvas({ ...canvas, nodes: [...canvas.nodes, secondNode], groups: [group], layerOrder: [group.id],
      edges: [{ id: crypto.randomUUID(), fromNode: canvas.nodes[0]!.id, toNode: secondNode.id, fromSide: 'right', toSide: 'left', toEnd: 'arrow', label: 'supports' }] });
    await fs.unlink(nodeDocumentPath);
    const reopened = new BrowserWindow({ width: 1280, height: 840, show: false, webPreferences: { preload: path.resolve('dist-electron/preload.cjs') } });
    await reopened.loadFile(path.resolve('dist/index.html'));
    for (let attempt = 0; attempt < 100; attempt += 1) {
      if (await reopened.webContents.executeJavaScript(`!!document.querySelector('.vault-root')`)) break;
      await new Promise((resolve) => setTimeout(resolve, 50));
    }
    assert.equal(await reopened.webContents.executeJavaScript(`!!document.querySelector('.vault-root') && !document.querySelector('[contenteditable=true]')`), true);
    await reopened.webContents.executeJavaScript(`Array.from(document.querySelectorAll('button')).find(b => b.textContent.trim() === 'Untitled.yantraC').click()`);
    await waitFor(`!!document.querySelector('.vault-live-missing-node') && !!document.querySelector('.react-flow__edge-path')`, reopened);
    assert.equal(await reopened.webContents.executeJavaScript(`document.querySelectorAll('.react-flow__node').length`), 2);
    assert.equal(await reopened.webContents.executeJavaScript(`!!document.querySelector('.group-outline__visible')`), true);
    assert.equal(await reopened.webContents.executeJavaScript(`document.querySelector('.vault-live-missing-node').parentElement.querySelector('[aria-label="Open Document"]').disabled`), true);
    await reopened.webContents.executeJavaScript(`document.querySelector('.react-flow__controls-fitview').click()`);
    await new Promise((resolve) => setTimeout(resolve, 400));
    await fs.writeFile(path.join(root, 'missing-reference.png'), (await reopened.webContents.capturePage()).toPNG());
    // Sidebar organization against the real filesystem: New Folder (submitted with Enter), Move To…, Rename.
    const evaluateReopened = (script: string) => reopened.webContents.executeJavaScript(script);
    const setDialogName = (name: string) => evaluateReopened(`(() => { const input = document.getElementById('vault-item-name'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, ${JSON.stringify(name)}); input.dispatchEvent(new Event('input', { bubbles: true })); })()`);
    const openRowMenu = (rowPath: string) => evaluateReopened(`(() => { const row = [...document.querySelectorAll('button[data-path]')].find(b => b.dataset.path === ${JSON.stringify(rowPath)}); const r = row.getBoundingClientRect(); row.dispatchEvent(new MouseEvent('contextmenu', { bubbles: true, cancelable: true, clientX: r.left + 20, clientY: r.top + 8 })); })()`);
    const clickMenuItem = (label: string) => evaluateReopened(`[...document.querySelectorAll('.vault-action-menu button')].find(b => b.textContent === ${JSON.stringify(label)}).click()`);
    await evaluateReopened(`[...document.querySelectorAll('button')].find(b => b.getAttribute('aria-label') === 'New Folder').click()`);
    await waitFor(`document.activeElement === document.getElementById('vault-item-name')`, reopened);
    await setDialogName('Archive');
    for (const type of ['keyDown', 'char', 'keyUp'] as const) reopened.webContents.sendInputEvent({ type, keyCode: 'Enter' });
    await waitFor(`!document.querySelector('.vault-dialog[open]') && !!document.querySelector('[data-path="Archive"]')`, reopened);
    assert.ok((await fs.stat(path.join(vaultPath, 'Archive'))).isDirectory());
    await openRowMenu(first.path);
    await waitFor(`!!document.querySelector('.vault-action-menu')`, reopened);
    await clickMenuItem('Rename');
    await waitFor(`!!document.getElementById('vault-item-name')`, reopened);
    await setDialogName('Broken');
    await evaluateReopened(`document.querySelector('.vault-dialog button[type="submit"]').click()`);
    await waitFor(`document.querySelector('.vault-dialog__error')?.textContent.includes('already exists')`, reopened);
    assert.equal(await evaluateReopened(`!!document.querySelector('.vault-dialog[open]')`), true);
    await evaluateReopened(`[...document.querySelectorAll('.vault-dialog button')].find(b => b.textContent === 'Cancel').click()`);
    await waitFor(`!document.querySelector('.vault-dialog[open]')`, reopened);
    await openRowMenu(first.path);
    await waitFor(`!!document.querySelector('.vault-action-menu')`, reopened);
    await clickMenuItem('Move To…');
    await waitFor(`!!document.querySelector('.vault-destination-list')`, reopened);
    await evaluateReopened(`[...document.querySelectorAll('.vault-destination-list input')].find(i => i.value === 'Archive').click()`);
    await evaluateReopened(`[...document.querySelectorAll('.vault-dialog button')].find(b => b.type === 'submit').click()`);
    await waitFor(`!!document.querySelector('[data-path="Archive/Independent_second_draft.yantraD"]') && !document.querySelector('.vault-dialog[open]')`, reopened);
    assert.match(await fs.readFile(path.join(vaultPath, 'Archive', 'Independent_second_draft.yantraD'), 'utf8'), /Independent second draft/);
    await openRowMenu('Archive/Independent_second_draft.yantraD');
    await waitFor(`!!document.querySelector('.vault-action-menu')`, reopened);
    await clickMenuItem('Rename');
    await waitFor(`document.getElementById('vault-item-name')?.value === 'Independent second draft'`, reopened);
    await setDialogName('Second draft 2');
    await evaluateReopened(`[...document.querySelectorAll('.vault-dialog button')].find(b => b.type === 'submit').click()`);
    await waitFor(`!!document.querySelector('[data-path="Archive/Second_draft_2.yantraD"]') && !document.querySelector('.vault-dialog[open]')`, reopened);
    const renamed = await fs.readFile(path.join(vaultPath, 'Archive', 'Second_draft_2.yantraD'), 'utf8');
    assert.match(renamed, /"title":\s*"Second_draft_2"/);
    assert.match(renamed, /Second draft 2/);
    await evaluateReopened(`document.querySelector('[data-path="Archive/Second_draft_2.yantraD"]').click()`);
    await waitFor(`document.querySelector('[contenteditable=true] h1')?.textContent === 'Second draft 2'`, reopened);
    await openRowMenu('Archive/Second_draft_2.yantraD');
    await waitFor(`!!document.querySelector('.vault-action-menu')`, reopened);
    await clickMenuItem('Rename');
    await waitFor(`document.getElementById('vault-item-name')?.value === 'Second draft 2'`, reopened);
    await setDialogName('Second draft 3');
    await evaluateReopened(`document.querySelector('.vault-dialog button[type="submit"]').click()`);
    await waitFor(`!document.querySelector('.vault-dialog[open]') && document.querySelector('[contenteditable=true] h1')?.textContent === 'Second draft 3'`, reopened);
    // Exercise the new lifecycle IPC without adding any production UI controls.
    const trashCandidate = await evaluateReopened(`(async () => {
      const value = result => { if (result.status !== 'success') throw new Error(JSON.stringify(result)); return result.value; };
      const vault = value(await window.yantraVault.restore());
      const invalidSession = await window.yantraVault.createDocument('expired-session', '');
      if (invalidSession.status !== 'failure' || invalidSession.error.code !== 'invalid-session') throw new Error('Typed session error was lost across IPC');
      const invalidName = await window.yantraVault.createFolder(vault.sessionId, '', 'Invalid name');
      if (invalidName.status !== 'failure' || invalidName.error.code !== 'invalid-input') throw new Error('Typed validation error was lost across IPC');
      const collision = await window.yantraVault.createFolder(vault.sessionId, '', 'Archive');
      if (collision.status !== 'failure' || collision.error.code !== 'collision') throw new Error('Typed collision error was lost across IPC');
      const created = value(await window.yantraVault.createDocument(vault.sessionId, ''));
      const moved = value(await window.yantraVault.renameEntry(vault.sessionId, created.path, 'Scope6Trash_' + crypto.randomUUID()));
      const refreshed = value(await window.yantraVault.refresh(vault.sessionId));
      if (!refreshed.entries.some(entry => entry.path === moved.to)) throw new Error('Refresh did not find test document');
      const deleted = value(await window.yantraVault.deleteEntry(vault.sessionId, moved.to));
      if (deleted.recovery || deleted.entries.some(entry => entry.path === moved.to)) throw new Error('System Trash deletion failed');
      const recovered = value(await window.yantraVault.retryRecovery(vault.sessionId));
      if (recovered.recovery) throw new Error('Unexpected pending recovery');
      return moved.to;
    })()`);
    await assert.rejects(fs.stat(path.join(vaultPath, trashCandidate)), { code: 'ENOENT' });
    reopened.destroy();
    console.log(`Vault UI smoke passed. Screenshots and isolated test vault: ${root}`);
    app.exit(0);
  } catch (error) {
    console.error(error);
    app.exit(1);
  }
}

void main().catch((error) => { console.error(error); app.exit(1); });
